language: python
python:
  - "3.6"

cache: pip

git:
  depth: 3

install:
  - pip install requests mkdocs mkdocs-material

"script":
  - python run.py skipimages
  - python -m mkdocs build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: site
  on:
    branch: master