language: python
python:
  - "3.6"

cache: pip

git:
  depth: 3

install:
  - pip install requests mkdocs mkdocs-material

"script":
  - python -m compileall ./tibiawiki-sql.py
  - python ./tibiawiki-sql.py skipimages
  - cat errors.log
  - python -m mkdocs build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: site
  on:
    branch: master