language: python
python:
  - "3.6"

cache: pip

install:
  - pip install requests mkdocs

stages:
  - test
  - deploy-docs

jobs:
  include:
    - stage: test
      script:
      - python -m compileall ./tibiawiki-sql.py
      - python ./tibiawiki-sql.py skipimages
      - cat errors.log
    - stage: deploy-docs
      script:
      - cp README.md docs/index.md
      - python -m mkdocs gh-deploy