language: python
python:
  - "3.6"

cache: pip

git:
  depth: 3

install:
  - pip install -U -r requirements.txt
  - pip install mkdocs mkdocs-material pymdown-extensions

"script":
  - python run.py generate --skip-images
  - cp CHANGELOG.md docs/changelog.md
  - python -m mkdocs build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep-history: true
  local_dir: site
  verbose: true
  on:
    branch: master