language: python
python:
  - "3.6"
  - "3.7-dev"

cache: pip

git:
  depth: 3

install:
  - pip install -U -r requirements.txt
  - pip install -U setuptools wheel
  - pip install coverage
  - pip install -U Sphinx

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - python setup.py sdist bdist_wheel
  - coverage run setup.py test
  - cd docs
  - make html
  - cd ..

after_script:
  - coverage report
  - coverage xml
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep-history: true
  local_dir: docs/_build/html
  verbose: true
  on:
    branch: master
    python: 3.6