language: python
python:
  - "3.6"

cache: pip

install:
  - pip install requests

jobs:
  include:
    - stage: test
      script: python -m compileall ./tibiawiki-sql.py
      - python ./tibiawiki-sql.py skipimages
      - cat errors.log
    - stage: deploy-docs
      script: cp README.md index.md
      - python -m mkdocs gh-deploy