language: python
python:
  - "3.6"

cache: pip

install:
  - pip install requests

"script":
- rm errors.log -f
- python -m compileall ./tibiawiki-sql.py
- python ./tibiawiki-sql.py skipimages
- echo "**************************"
- echo "*      error.log         *"
- echo "**************************"
- cat errors.log