site_name: tibiawiki-sql
site_description: A sqlite database generator based on TibiaWiki articles.
site_author: Allan Galarza

site_name: tibiawiki-sql
theme:
  name: material
  palette:
    primary: 'red'
    accent: 'green'
  logo:
    icon: 'info'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/Galarzaa90/tibiawiki-sql'
    - type: 'gitlab'
      link: 'https://gitlab.com/Galarzaa90/tibiawiki-sql'
    - type: 'cubes'
      link: 'https://pypi.org/project/tibiawikisql/'

repo_url: https://github.com/Galarzaa90/tibiawiki-sql
edit_uri: ""
pages:
    - Home: index.md
    - Changelog: changelog.md
    - Schema: schema.md
    - Queries: queries.md
