name: Build Database
on:
  push:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python runtime
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install module
        run: python setup.py install

      - name: Cache Images
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/images
          key: images-cache

      - name: Generate Database
        run: tibiawikisql generate

      - name: Upload database
        uses: actions/upload-artifact@v2
        with:
          name: tibiawiki-db
          path: |
            tibiawiki.db
            images/
